## Torch

In [3]:
!pip install torch

In [1]:
import torch
torch.__version__

'1.2.0'

In [15]:
## pytorch_qa
# torch_model = torch.load("./pytorch_model.bin",map_location='cpu')# luke github官方上面提供的squad微调后权重
# torch_model


OrderedDict([('encoder.layer.0.attention.self.query.weight',
              tensor([[-0.0034,  0.0348,  0.0006,  ...,  0.0017,  0.0590, -0.0426],
                      [-0.0249,  0.0531, -0.0148,  ..., -0.0304, -0.0145,  0.0117],
                      [ 0.0062,  0.0708, -0.0332,  ...,  0.0803,  0.0118, -0.0132],
                      ...,
                      [-0.0585,  0.0210, -0.0427,  ..., -0.0298,  0.0051,  0.0694],
                      [ 0.0424,  0.0232, -0.0613,  ..., -0.0552, -0.0157,  0.0171],
                      [-0.0183, -0.0454, -0.0102,  ...,  0.0471,  0.0229, -0.0177]])),
             ('encoder.layer.0.attention.self.query.bias',
              tensor([ 0.3127,  0.0561, -0.0748,  ..., -0.0707, -0.0500, -0.0668])),
             ('encoder.layer.0.attention.self.key.weight',
              tensor([[-0.0044, -0.0183, -0.0138,  ..., -0.0041,  0.0094, -0.0148],
                      [-0.0240, -0.0002,  0.0252,  ...,  0.0400,  0.0435, -0.0201],
                      [-0.0266, -0

In [3]:
## pytorch_luke ori
torch_model = torch.load("./torch2ms/pytorch_model.bin",map_location='cpu')# luke github官方上面提供的squad微调后权重
torch_model

OrderedDict([('encoder.layer.0.attention.self.query.weight',
              tensor([[-0.0029,  0.0352,  0.0007,  ...,  0.0023,  0.0595, -0.0426],
                      [-0.0248,  0.0529, -0.0145,  ..., -0.0303, -0.0143,  0.0116],
                      [ 0.0061,  0.0708, -0.0336,  ...,  0.0807,  0.0115, -0.0131],
                      ...,
                      [-0.0589,  0.0206, -0.0426,  ..., -0.0298,  0.0041,  0.0700],
                      [ 0.0421,  0.0225, -0.0608,  ..., -0.0552, -0.0157,  0.0173],
                      [-0.0184, -0.0457, -0.0103,  ...,  0.0474,  0.0225, -0.0182]])),
             ('encoder.layer.0.attention.self.query.bias',
              tensor([ 0.3121,  0.0556, -0.0751,  ..., -0.0704, -0.0500, -0.0664])),
             ('encoder.layer.0.attention.self.key.weight',
              tensor([[-0.0043, -0.0184, -0.0136,  ..., -0.0037,  0.0096, -0.0156],
                      [-0.0238, -0.0002,  0.0253,  ...,  0.0403,  0.0436, -0.0195],
                      [-0.0264, -0

In [4]:
torch_model['embeddings.word_embeddings.weight'].shape

torch.Size([50265, 1024])

In [21]:
torch_model['encoder.layer.0.attention.self.query.weight'].shape

torch.Size([1024, 1024])

In [22]:
torch_model['encoder.layer.0.attention.self.query.bias'].shape

torch.Size([1024])

In [23]:
torch_model['encoder.layer.0.attention.self.key.weight'].shape

torch.Size([1024, 1024])

In [24]:
torch_model['encoder.layer.0.attention.self.key.bias'].shape

torch.Size([1024])

In [25]:
torch_model['encoder.layer.0.attention.self.value.weight'].shape

torch.Size([1024, 1024])

In [26]:
torch_model['encoder.layer.0.attention.self.value.bias'].shape

torch.Size([1024])

In [27]:
torch_model['encoder.layer.0.attention.self.w2e_query.weight'].shape

torch.Size([1024, 1024])

In [28]:
torch_model['encoder.layer.0.attention.self.w2e_query.bias'].shape

torch.Size([1024])

In [29]:
torch_model['encoder.layer.0.attention.self.e2w_query.weight'].shape

torch.Size([1024, 1024])

In [30]:
torch_model['encoder.layer.0.attention.self.e2w_query.bias'].shape

torch.Size([1024])

In [31]:
torch_model['encoder.layer.0.attention.self.e2e_query.weight'].shape

torch.Size([1024, 1024])

In [32]:
torch_model['encoder.layer.0.attention.self.e2e_query.bias'].shape

torch.Size([1024])

In [33]:
torch_model['encoder.layer.0.attention.output.dense.weight'].shape

torch.Size([1024, 1024])

In [34]:
torch_model['encoder.layer.0.attention.output.dense.bias'].shape

torch.Size([1024])

In [35]:
torch_model['encoder.layer.0.attention.output.LayerNorm.weight'].shape

torch.Size([1024])

In [36]:
torch_model['encoder.layer.0.attention.output.LayerNorm.bias'].shape

torch.Size([1024])

In [37]:
torch_model['encoder.layer.0.intermediate.dense.weight'].shape

torch.Size([4096, 1024])

In [38]:
torch_model['encoder.layer.0.intermediate.dense.bias'].shape

torch.Size([4096])

In [39]:
torch_model['encoder.layer.0.output.dense.weight'].shape

torch.Size([1024, 4096])

In [40]:
torch_model['encoder.layer.0.output.dense.bias'].shape

torch.Size([1024])

In [41]:
torch_model['encoder.layer.0.output.LayerNorm.weight'].shape

torch.Size([1024])

In [42]:
torch_model['encoder.layer.0.output.LayerNorm.bias'].shape

torch.Size([1024])

In [11]:
#  for weight_name, weight_value in torch_model.items():
#         print(weight_value.shape)
#         y=weight_value.numpy()
#         print(y)

## mindspore

In [5]:
from readingcomprehension.models.luke import LukeForReadingComprehension
import mindspore.common.dtype as mstype
from model.bert_model import BertConfig
from mindspore import context
from model.luke import LukeModel, EntityAwareEncoder
import numpy as np
from mindspore import Tensor, context
from mindspore import dtype as mstype
import mindspore.ops as ops
import mindspore.nn as nn
from model.bert_model import BertOutput
from mindspore.common.initializer import TruncatedNormal
import math
from mindspore.ops import composite as C
import mindspore
from mindspore.ops import operations as P
context.set_context(mode=context.GRAPH_MODE, device_target="CPU")

[WARNING] ME(6693:140567675840320,MainProcess):2021-10-26-11:15:57.114.192 [mindspore/run_check/_check_version.py:181] Cuda ['10.1', '11.1'] version(need by mindspore-gpu) is not found, please confirm that the path of cuda is set to the env LD_LIBRARY_PATH, please refer to the installation guidelines: https://www.mindspore.cn/install
[WARNING] ME(6693:140567675840320,MainProcess):2021-10-26-11:15:57.158.977 [mindspore/run_check/_check_version.py:181] Cuda ['10.1', '11.1'] version(need by mindspore-gpu) is not found, please confirm that the path of cuda is set to the env LD_LIBRARY_PATH, please refer to the installation guidelines: https://www.mindspore.cn/install


In [6]:
config = BertConfig()
model = LukeForReadingComprehension(config)

In [7]:
config.num_attention_heads

16

In [8]:
ms_model = model.parameters_dict()
ms_model

OrderedDict([('luke.embeddings.word_embeddings.embedding_table',
              Parameter (name=luke.embeddings.word_embeddings.embedding_table, shape=(50265, 1024), dtype=Float32, requires_grad=True)),
             ('luke.embeddings.position_embeddings.embedding_table',
              Parameter (name=luke.embeddings.position_embeddings.embedding_table, shape=(514, 1024), dtype=Float32, requires_grad=True)),
             ('luke.embeddings.token_type_embeddings.embedding_table',
              Parameter (name=luke.embeddings.token_type_embeddings.embedding_table, shape=(1, 1024), dtype=Float32, requires_grad=True)),
             ('luke.embeddings.layer_norm.gamma',
              Parameter (name=luke.embeddings.layer_norm.gamma, shape=(1024,), dtype=Float32, requires_grad=True)),
             ('luke.embeddings.layer_norm.beta',
              Parameter (name=luke.embeddings.layer_norm.beta, shape=(1024,), dtype=Float32, requires_grad=True)),
             ('luke.entity_embeddings.entity_embed

In [20]:
ms_model['embeddings.word_embeddings.embedding_table']

KeyError: 'embeddings.word_embeddings.embedding_table'

In [ ]:
ms_model['encoder.layer.0.output.dense.weight']

## torch2ms

In [9]:
import os
import collections
from mindspore import log as logger
from mindspore.common.tensor import Tensor
from mindspore.common.initializer import initializer
from mindspore import save_checkpoint
from mindspore import Parameter

In [10]:
def build_params_map(layer_num=24):
    """
    build params map from torch's LUKE to mindspore's LUKE
    map=> key：value，torch_name：ms_name
    键：torch权重名称，值：mindspore权重名称
    :return:
    """
    weight_map = collections.OrderedDict({
        'embeddings.word_embeddings.weight': "luke.embeddings.word_embeddings.embedding_table",
        'embeddings.position_embeddings.weight': "luke.embeddings.position_embeddings.embedding_table",
        'embeddings.token_type_embeddings.weight': "luke.embeddings.token_type_embeddings.embedding_table",
        'embeddings.LayerNorm.weight': 'luke.embeddings.layer_norm.gamma',
        'embeddings.LayerNorm.bias': 'luke.embeddings.layer_norm.beta',
        'entity_embeddings.entity_embeddings.weight':'luke.entity_embeddings.entity_embeddings.embedding_table',
        'entity_embeddings.entity_embedding_dense.weight':'luke.entity_embeddings.entity_embedding_dense.weight',
        'entity_embeddings.position_embeddings.weight':'luke.entity_embeddings.position_embeddings.embedding_table',
        'entity_embeddings.token_type_embeddings.weight':'luke.entity_embeddings.token_type_embeddings.embedding_table',
        'entity_embeddings.LayerNorm.weight':'luke.entity_embeddings.layer_norm.gamma',
        'entity_embeddings.LayerNorm.bias':'luke.entity_embeddings.layer_norm.beta',
        'qa_outputs.weight':'qa_outputs.weight',
        'qa_outputs.bias':'qa_outputs.bias',
#         'pooler.dense.weight':'pooler.weight',
#         'pooler.dense.bias':'pooler.bias'
        
    })
    
    # add attention layers
    for i in range(layer_num):
        weight_map[f'encoder.layer.{i}.attention.self.query.weight'] = \
            f'luke.encoder.layer.{i}.attention.self_attention.query.weight'
        weight_map[f'encoder.layer.{i}.attention.self.query.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.query.bias'
        weight_map[f'encoder.layer.{i}.attention.self.key.weight']= \
            f'luke.encoder.layer.{i}.attention.self_attention.key.weight'
        weight_map[f'encoder.layer.{i}.attention.self.key.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.key.bias'
        weight_map[f'encoder.layer.{i}.attention.self.value.weight']= \
            f'luke.encoder.layer.{i}.attention.self_attention.value.weight'
        weight_map[f'encoder.layer.{i}.attention.self.value.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.value.bias'
        weight_map[f'encoder.layer.{i}.attention.self.w2e_query.weight']= \
            f'luke.encoder.layer.{i}.attention.self_attention.w2e_query.weight'
        weight_map[f'encoder.layer.{i}.attention.self.w2e_query.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.w2e_query.bias'
        weight_map[f'encoder.layer.{i}.attention.self.e2w_query.weight']= \
            f'luke.encoder.layer.{i}.attention.self_attention.e2w_query.weight'
        weight_map[f'encoder.layer.{i}.attention.self.e2w_query.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.e2w_query.bias'
        weight_map[f'encoder.layer.{i}.attention.self.e2e_query.weight']= \
            f'luke.encoder.layer.{i}.attention.self_attention.e2e_query.weight'
        weight_map[f'encoder.layer.{i}.attention.self.e2e_query.bias']= \
            f'luke.encoder.layer.{i}.attention.self_attention.e2e_query.bias'
        weight_map[f'encoder.layer.{i}.attention.output.dense.weight']= \
            f'luke.encoder.layer.{i}.attention.output.dense.weight'
        weight_map[f'encoder.layer.{i}.attention.output.dense.bias'] = \
            f'luke.encoder.layer.{i}.attention.output.dense.bias'
        weight_map[f'encoder.layer.{i}.attention.output.LayerNorm.weight'] = \
            f'luke.encoder.layer.{i}.attention.output.layernorm.gamma'
        weight_map[f'encoder.layer.{i}.attention.output.LayerNorm.bias'] = \
            f'luke.encoder.layer.{i}.attention.output.layernorm.beta'
        weight_map[f'encoder.layer.{i}.intermediate.dense.weight'] = \
            f'luke.encoder.layer.{i}.intermediate.weight'
        weight_map[f'encoder.layer.{i}.intermediate.dense.bias'] = \
            f'luke.encoder.layer.{i}.intermediate.bias'
        weight_map[f'encoder.layer.{i}.output.dense.weight'] = \
            f'luke.encoder.layer.{i}.output.dense.weight'
        weight_map[f'encoder.layer.{i}.output.dense.bias'] = \
            f'luke.encoder.layer.{i}.output.dense.bias'
        weight_map[f'encoder.layer.{i}.output.LayerNorm.weight'] = \
            f'luke.encoder.layer.{i}.output.layernorm.gamma'
        weight_map[f'encoder.layer.{i}.output.LayerNorm.bias'] = \
            f'luke.encoder.layer.{i}.output.layernorm.beta'
    # add pooler
#     weight_map.update(
#         {
#             'pooled_fc.w_0': 'ernie.ernie.dense.weight',
#             'pooled_fc.b_0': 'ernie.ernie.dense.bias',
#             'cls_out_w': 'ernie.dense_1.weight',
#             'cls_out_b': 'ernie.dense_1.bias'
#         }
#    )
    return weight_map

In [11]:
def _update_param(param, new_param):
    """Updates param's data from new_param's data."""

    if isinstance(param.data, Tensor) and isinstance(new_param.data, Tensor):
        if param.data.dtype != new_param.data.dtype:
            logger.error("Failed to combine the net and the parameters for param %s.", param.name)
            msg = ("Net parameters {} type({}) different from parameter_dict's({})"
                   .format(param.name, param.data.dtype, new_param.data.dtype))
            raise RuntimeError(msg)

        if param.data.shape != new_param.data.shape:
            if not _special_process_par(param, new_param):
                logger.error("Failed to combine the net and the parameters for param %s.", param.name)
                msg = ("Net parameters {} shape({}) different from parameter_dict's({})"
                       .format(param.name, param.data.shape, new_param.data.shape))
                raise RuntimeError(msg)
            return

        param.set_data(new_param.data)
        return

    if isinstance(param.data, Tensor) and not isinstance(new_param.data, Tensor):
        if param.data.shape != (1,) and param.data.shape != ():
            logger.error("Failed to combine the net and the parameters for param %s.", param.name)
            msg = ("Net parameters {} shape({}) is not (1,), inconsistent with parameter_dict's(scalar)."
                   .format(param.name, param.data.shape))
            raise RuntimeError(msg)
        param.set_data(initializer(new_param.data, param.data.shape, param.data.dtype))

    elif isinstance(new_param.data, Tensor) and not isinstance(param.data, Tensor):
        logger.error("Failed to combine the net and the parameters for param %s.", param.name)
        msg = ("Net parameters {} type({}) different from parameter_dict's({})"
               .format(param.name, type(param.data), type(new_param.data)))
        raise RuntimeError(msg)

    else:
        param.set_data(type(param.data)(new_param.data))


def _special_process_par(par, new_par):
    """
    Processes the special condition.

    Like (12,2048,1,1)->(12,2048), this case is caused by GE 4 dimensions tensor.
    """
    par_shape_len = len(par.data.shape)
    new_par_shape_len = len(new_par.data.shape)
    delta_len = new_par_shape_len - par_shape_len
    delta_i = 0
    for delta_i in range(delta_len):
        if new_par.data.shape[par_shape_len + delta_i] != 1:
            break
    if delta_i == delta_len - 1:
        new_val = new_par.data.asnumpy()
        new_val = new_val.reshape(par.data.shape)
        par.set_data(Tensor(new_val, par.data.dtype))
        return True
    return False

In [13]:
def extract_and_convert(torch_model, ms_model):
    """extract weights and convert to mindspore"""
    print('=' * 20 + 'extract weights' + '=' * 20)
    state_dict = []
    weight_map = build_params_map(layer_num=24)
    
    for weight_name, weight_value in torch_model.items():
        if weight_name not in weight_map.keys():
            continue
       
        state_dict.append({'name': weight_map[weight_name], 'data': Tensor(weight_value.numpy())})
        value = Parameter(Tensor(weight_value.numpy()),name=weight_map[weight_name])
        key = ms_model[weight_map[weight_name]]
        _update_param(key, value)
        print(weight_name, '->', weight_map[weight_name], weight_value.shape)
        
    # save_checkpoint(model, os.path.join("./luke-large-qa.ckpt"))
    save_checkpoint(model, os.path.join("./luke-large.ckpt"))
    print('=' * 20 + 'extract weights finished' + '=' * 20)

In [14]:
extract_and_convert(torch_model,ms_model)

====================extract weights====================
encoder.layer.0.attention.self.query.weight -> luke.encoder.layer.0.attention.self_attention.query.weight torch.Size([1024, 1024])
encoder.layer.0.attention.self.query.bias -> luke.encoder.layer.0.attention.self_attention.query.bias torch.Size([1024])
encoder.layer.0.attention.self.key.weight -> luke.encoder.layer.0.attention.self_attention.key.weight torch.Size([1024, 1024])
encoder.layer.0.attention.self.key.bias -> luke.encoder.layer.0.attention.self_attention.key.bias torch.Size([1024])
encoder.layer.0.attention.self.value.weight -> luke.encoder.layer.0.attention.self_attention.value.weight torch.Size([1024, 1024])
encoder.layer.0.attention.self.value.bias -> luke.encoder.layer.0.attention.self_attention.value.bias torch.Size([1024])
encoder.layer.0.attention.output.dense.weight -> luke.encoder.layer.0.attention.output.dense.weight torch.Size([1024, 1024])
encoder.layer.0.attention.output.dense.bias -> luke.encoder.layer.0.att

encoder.layer.5.intermediate.dense.weight -> luke.encoder.layer.5.intermediate.weight torch.Size([4096, 1024])
encoder.layer.5.intermediate.dense.bias -> luke.encoder.layer.5.intermediate.bias torch.Size([4096])
encoder.layer.5.output.dense.weight -> luke.encoder.layer.5.output.dense.weight torch.Size([1024, 4096])
encoder.layer.5.output.dense.bias -> luke.encoder.layer.5.output.dense.bias torch.Size([1024])
encoder.layer.5.output.LayerNorm.weight -> luke.encoder.layer.5.output.layernorm.gamma torch.Size([1024])
encoder.layer.5.output.LayerNorm.bias -> luke.encoder.layer.5.output.layernorm.beta torch.Size([1024])
encoder.layer.6.attention.self.query.weight -> luke.encoder.layer.6.attention.self_attention.query.weight torch.Size([1024, 1024])
encoder.layer.6.attention.self.query.bias -> luke.encoder.layer.6.attention.self_attention.query.bias torch.Size([1024])
encoder.layer.6.attention.self.key.weight -> luke.encoder.layer.6.attention.self_attention.key.weight torch.Size([1024, 1024])


encoder.layer.12.output.dense.weight -> luke.encoder.layer.12.output.dense.weight torch.Size([1024, 4096])
encoder.layer.12.output.dense.bias -> luke.encoder.layer.12.output.dense.bias torch.Size([1024])
encoder.layer.12.output.LayerNorm.weight -> luke.encoder.layer.12.output.layernorm.gamma torch.Size([1024])
encoder.layer.12.output.LayerNorm.bias -> luke.encoder.layer.12.output.layernorm.beta torch.Size([1024])
encoder.layer.13.attention.self.query.weight -> luke.encoder.layer.13.attention.self_attention.query.weight torch.Size([1024, 1024])
encoder.layer.13.attention.self.query.bias -> luke.encoder.layer.13.attention.self_attention.query.bias torch.Size([1024])
encoder.layer.13.attention.self.key.weight -> luke.encoder.layer.13.attention.self_attention.key.weight torch.Size([1024, 1024])
encoder.layer.13.attention.self.key.bias -> luke.encoder.layer.13.attention.self_attention.key.bias torch.Size([1024])
encoder.layer.13.attention.self.value.weight -> luke.encoder.layer.13.attention

encoder.layer.19.intermediate.dense.weight -> luke.encoder.layer.19.intermediate.weight torch.Size([4096, 1024])
encoder.layer.19.intermediate.dense.bias -> luke.encoder.layer.19.intermediate.bias torch.Size([4096])
encoder.layer.19.output.dense.weight -> luke.encoder.layer.19.output.dense.weight torch.Size([1024, 4096])
encoder.layer.19.output.dense.bias -> luke.encoder.layer.19.output.dense.bias torch.Size([1024])
encoder.layer.19.output.LayerNorm.weight -> luke.encoder.layer.19.output.layernorm.gamma torch.Size([1024])
encoder.layer.19.output.LayerNorm.bias -> luke.encoder.layer.19.output.layernorm.beta torch.Size([1024])
encoder.layer.20.attention.self.query.weight -> luke.encoder.layer.20.attention.self_attention.query.weight torch.Size([1024, 1024])
encoder.layer.20.attention.self.query.bias -> luke.encoder.layer.20.attention.self_attention.query.bias torch.Size([1024])
encoder.layer.20.attention.self.key.weight -> luke.encoder.layer.20.attention.self_attention.key.weight torch.S

embeddings.word_embeddings.weight -> luke.embeddings.word_embeddings.embedding_table torch.Size([50265, 1024])
embeddings.position_embeddings.weight -> luke.embeddings.position_embeddings.embedding_table torch.Size([514, 1024])
embeddings.token_type_embeddings.weight -> luke.embeddings.token_type_embeddings.embedding_table torch.Size([1, 1024])
embeddings.LayerNorm.weight -> luke.embeddings.layer_norm.gamma torch.Size([1024])
embeddings.LayerNorm.bias -> luke.embeddings.layer_norm.beta torch.Size([1024])
entity_embeddings.entity_embeddings.weight -> luke.entity_embeddings.entity_embeddings.embedding_table torch.Size([500000, 256])
entity_embeddings.entity_embedding_dense.weight -> luke.entity_embeddings.entity_embedding_dense.weight torch.Size([1024, 256])
entity_embeddings.position_embeddings.weight -> luke.entity_embeddings.position_embeddings.embedding_table torch.Size([514, 1024])
entity_embeddings.token_type_embeddings.weight -> luke.entity_embeddings.token_type_embeddings.embeddi